theme: jekyll-theme-primer
title: Python for Neuroscience
description: Learning python for neuroscience without all the extraneous datascience, web development, and other stuff that you don't need to know.